name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'khidma-backend/package-lock.json'

    - name: Install dependencies
      run: cd khidma-backend && npm ci

    - name: Run linter
      run: cd khidma-backend && npm run lint

    - name: Run build
      run: cd khidma-backend && npm run build

    - name: Run tests
      run: cd khidma-backend && npm test
